import React, { useState } from "react";
import { Link, NavLink } from "react-router-dom";
import { marked } from "marked";
import DOMPurify from "dompurify";
import "github-markdown-css/github-markdown-dark.css";
import "../styles/Generator.css";
import Navbar from "../components/Navbar";

const Generator = () => {
  const [repoUrl, setRepoUrl] = useState("");
  const [customInstructions, setCustomInstructions] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [markdownOutput, setMarkdownOutput] = useState('');
  const [activeTab, setActiveTab] = useState('code');
  const [copied, setCopied] = useState(false);
  const [downloaded, setDownloaded] = useState(false);

  const handleGenerate = () => {
    setIsGenerating(true);
    setTimeout(() => {
      setMarkdownOutput(
        `# Documentation for: ${repoUrl || "Repository"}\n\n## Overview\nThis documentation was automatically generated by AutoDoc.ai.\n\n## Installation\n\`\`\`bash\ngit clone ${repoUrl || "https://github.com/username/repository"}\ncd repository\nnpm install\n\`\`\`\n\n## Usage\nBasic usage instructions will appear here once your repository is analyzed.\n\n## API Reference\nAPI documentation will be generated automatically.\n\n## Contributing\nGuidelines for contributions will be populated based on repository analysis.\n`,
      );
      setIsGenerating(false);
    }, 2000);
  };

  const handleCopyCode = () => {
    if (!markdownOutput) return;
    navigator.clipboard.writeText(markdownOutput);
    setCopied(true);
    setTimeout(() => {
      setCopied(false);
    }, 2000);
  };

  const handleDownloadFile = () => {
    if (!markdownOutput) return;

    let fileName = 'README.md';
    if (repoUrl) {
      try {
        const parts = repoUrl.trim().split('/');
        const repoName = parts[parts.length - 1] || parts[parts.length - 2];
        if (repoName) {
          fileName = `${repoName.replace(/\.git$/, '')}-README.md`;
        }
      } catch (error) {
        fileName = 'README.md';
      }
    }

    const blob = new Blob([markdownOutput], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = fileName;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    setDownloaded(true);
    setTimeout(() => {
      setDownloaded(false);
    }, 2000);
  };

  return (
    <div className="generator-container">
      <Navbar />

      <main className="workspace">
        <div className="control-panel">
          <h2 className="panel-title">Repository Configuration</h2>

          <div className="input-group">
            <label htmlFor="repo-url">GitHub Repository URL</label>
            <input
              id="repo-url"
              type="url"
              placeholder="https://github.com/username/repository"
              value={repoUrl}
              onChange={(e) => setRepoUrl(e.target.value)}
              className="text-input"
            />
          </div>

          <div className="input-group">
            <label htmlFor="custom-instructions">
              Custom Instructions (Optional)
            </label>
            <textarea
              id="custom-instructions"
              placeholder="Add any specific requirements or focus areas for the documentation..."
              value={customInstructions}
              onChange={(e) => setCustomInstructions(e.target.value)}
              className="text-textarea"
              rows={5}
            />
          </div>

          <button
            onClick={handleGenerate}
            disabled={isGenerating}
            className="btn btn-primary generate-btn"
          >
            {isGenerating ? (
              <>
                <span className="spinner"></span>
                Generating...
              </>
            ) : (
              "Generate Documentation"
            )}
          </button>
        </div>

        <div className="output-panel">
          <div className="output-header">
            <div className="output-header-left">
              <h3>Generated Documentation</h3>
              <div className="tabs">
                <button
                  onClick={() => setActiveTab('code')}
                  className={`tab-button ${activeTab === 'code' ? 'active' : ''}`}
                >
                  Code
                </button>
                <button
                  onClick={() => setActiveTab('preview')}
                  className={`tab-button ${activeTab === 'preview' ? 'active' : ''}`}
                >
                  Preview
                </button>
              </div>
            </div>
            <div className="output-header-actions">
              <div className={`tooltip-wrapper ${copied ? 'show-success' : ''}`}>
                <button
                  onClick={handleCopyCode}
                  disabled={!markdownOutput}
                  className="btn-copy-icon"
                  aria-label="Copy code"
                >
                  <svg
                    stroke="currentColor"
                    fill="none"
                    strokeWidth="2"
                    viewBox="0 0 24 24"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    height="1em"
                    width="1em"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect>
                    <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path>
                  </svg>
                </button>
                <span className="tooltip-text">{copied ? 'Copied!' : 'Copy Code'}</span>
              </div>

              <div className={`tooltip-wrapper ${downloaded ? 'show-success' : ''}`}>
                <button
                  onClick={handleDownloadFile}
                  disabled={!markdownOutput}
                  className="btn-copy-icon"
                  aria-label="Download file"
                >
                  <svg
                    stroke="currentColor"
                    fill="none"
                    strokeWidth="2"
                    viewBox="0 0 24 24"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    height="1em"
                    width="1em"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path>
                    <polyline points="7 10 12 15 17 10"></polyline>
                    <line x1="12" y1="15" x2="12" y2="3"></line>
                  </svg>
                </button>
                <span className="tooltip-text">{downloaded ? 'Downloaded!' : 'Download File'}</span>
              </div>
            </div>
          </div>
          {activeTab === 'code' ? (
            <pre className="output-content">
              <code>{markdownOutput || '# Your documentation will appear here...'}</code>
            </pre>
          ) : (
            <div
              className="output-content markdown-body"
              dangerouslySetInnerHTML={{
                __html: DOMPurify.sanitize(marked.parse(markdownOutput || '# Your documentation will appear here...')),
              }}
            />
          )}
        </div>
      </main>
    </div>
  );
};

export default Generator;
